package com.studying.utilitybillsbot;

public enum BillsStatus implements IStatus {

  NONE, WAITING_ELECTRICITY, WAITING_COLD_WATER, WAITING_HOT_WATER, WAITING_GAS,
  EDITING, EDITING_ELECTRICITY_FIRST, EDITING_ELECTRICITY_LAST, EDITING_COLD_WATER_FIRST, EDITING_COLD_WATER_LAST,
  EDITING_HOT_WATER_FIRST, EDITING_HOT_WATER_LAST, EDITING_GAS_FIRST, EDITING_GAS_LAST

}
