package com.studying.utilitybillsbot;

public enum BillsStatus implements IStatus{

  NONE, WAITING_ELECTRICITY, WAITING_COLD_WATER, WAITING_HOT_WATER, WAITING_GAS, EDITING, EDITING_ELECTRICITY, EDITING_COLD_WATER, EDITING_HOT_WATER, EDITING_GAS

}
