package com.studying.utilitybillsbot;

public enum RatesStatus implements IStatus {

  NONE, WAITING_ELECTRICITY_RATE, WAITING_COLD_WATER_RATE, WAITING_HOT_WATER_RATE, WAITING_GAS_RATE, COMPLETED, EDITING, EDITING_ELECTRICITY_RATE, EDITING_COLD_WATER_RATE, EDITING_HOT_WATER_RATE, EDITING_GAS_RATE

}
