services:
  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/utility-bills-bot-db?connectTimeout=10&socketTimeout=10
      SPRING_DATASOURCE_USERNAME: frostbjorne
      SPRING_DATASOURCE_PASSWORD: frostbjorne

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: frostbjorne
      POSTGRES_USER: frostbjorne
      POSTGRES_DB: utility-bills-bot-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U frostbjorne -d utility-bills-bot-db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - utility-bills-bot-db-data:/var/lib/postgresql/data

volumes:
  utility-bills-bot-db-data:
